# spring
spring:
  application:
    name: fish
  # profile active dev
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect

# tomcat
server:
  address: 127.0.0.1
  port: 12001
  tomcat:
    basedir: ${user.home}/fish/tmp

# log
logging:
  file: ${user.home}/fish/fish.log
  level.com.nekolr: info
