# spring
spring:
  application:
    name: fish
  # profile active dev
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: 10000
        max-idle: 8
      shutdown-timeout: 100
  cache:
    redis:
      time-to-live: 1d
      cache-null-values: false


# tomcat
server:
  address: 127.0.0.1
  port: 12001
  tomcat:
    basedir: ${user.home}/fish/tmp

# log
logging:
  file: ${user.home}/fish/fish.log
  level.com.nekolr: debug
